# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90f4f0b21c0c4f39793a600f3bdcc1c12d17e11df0a5d6fd93c2f58a447383ecc3b4b8952881fbd6b1f65bc588f4ea90091651f1c740d413a05b73faeb03415c

test:
  secret_key_base: 118faca66709d758721c1fb37e1fadf82e65fc0d9d68fadcf7e6be49942a74421883ed2e51d96035a7e4169c0e1026b823f42921c7a59a3e365a00a43f520425

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
